### ISSUE TITLE
upgrading to 1.1.0 broke all snippets with https:// url

### ISSUE THREAD

**Issue by berteh** [infostreams/snippets#1]
Hello,
as said in the title: updating to snippets 1.1.0 broke all snippets that have a url with https:// in the parameters, such as
(file: https://bitcoin.org/bitcoin.pdf) (link: https://github.com/leaflet-extras/)

They generate file->./https and link->./https
thanks for the otherwise great plugin!
B.

**Comment by infostreams** [comment]
Sorry! I wasn't actually aware that anyone was using this, so I didn't bother with backwards compatibility too much. What happens when you quote the parameter values? Just out of curiosity - I will address this issue and fix it, probably tomorrow.

**Comment by infostreams** [comment]
I've fixed this issue in 1.1.1 - please update and re-open if it doesn't work for you.

**Comment by jacmoe** [comment]
Thanks for this fix! :+1: 
I am using it too - great plugin! :)

I wanted to open an issue because I had some problems getting youtubes and vimeos to work, but after a quick composer update it was fixed. Awesome!

**Comment by berteh** [comment]
works indeed. thank you!
